#!/bin/env bash

declare -a QPIDS

BIN=$(readlink -f -- $(dirname -- "$0"))

export TZ=Asia/Shanghai
export LC_ALL='en_US.UTF8'

export LD_LIBRARY_PATH=/opt/qcontent/lib:$LD_LIBRARY_PATH
export PATH=/opt/qcontent/bin:$PATH
export DISPLAY=:99

LOG_DIR=/export/m4/qthumbextractor-log/
test -d $LOG_DIR || mkdir -p $LOG_DIR

export GLOG_log_dir=$LOG_DIR

#qextractor -d --conf $BIN/../etc/qextractor.conf
#exit 0

PROCESSES=$1
ulimit -c 1000000

if [ -z $PROCESSES ]; then
    echo "Usage: $0 <num>";
    exit 1;
else
    for i in  `seq 0 $(($PROCESSES - 1 ))`;
    do
	    qextractor --conf $BIN/../etc/qthumbextractor.conf &
        QPIDS[$i]=$!
        sleep 1;
    done
fi

sleep 5

### monitor
while true
do
    for i in  `seq 0 $(($PROCESSES - 1 ))`
    do
        kill -0 ${QPIDS[$i]} 2>/dev/null
        if [ $? -ne 0 ]
        then
	        qextractor --conf $BIN/../etc/qthumbextractor.conf &
            QPIDS[$i]=$!
        fi
        sleep 5;
    done
    sleep 300;
done
